{
 "title": "GraphQL Echo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "targetHeader",
    "label": "Target Header",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Basic Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Expected Headers",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "echoHttpHeaders",
       "timeFields": []
      }
     ],
     "queryText": "query ($targetHeader: String!){\n  echoHttpHeaders {\n    targetHeader:getHeader(name:$targetHeader)\n    \n  \thost:expectHeader(name:\"host\")\n    userAgent:expectHeader(name:\"user-agent\")\n    contentType:expectHeader(name:\"Content-Type\")\n    contentLength:expectHeader(name:\"content-length\")\n    accept:expectHeader(name:\"accept\")\n    acceptEncoding:expectHeader(name:\"accept-encoding\")\n    \n    # These headers are not present on Grafana 9.3.X\n    datasourceUid:getHeader(name:\"x-datasource-uid\")\n    panelId:getHeader(name:\"x-panel-id\")\n  }\n}\n",
     "variables": "{\n  \"targetHeader\": \"$targetHeader\"\n}"
    }
   ]
  },
  {
   "title": "All headers",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "echoHttpHeaders.entries",
       "timeFields": []
      }
     ],
     "queryText": "query {\n  echoHttpHeaders {\n    entries {\n      name\n      values\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Generated Processor Temperatures (Uses \"Partition by values\" transform)",
   "type": "timeseries",
   "description": "Note: The labels do not appear correctly on Grafana 9.3",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "generateDummyTimeseries",
       "explodeArrayPaths": [
        "nodeData.datapoints.processorTemperatures"
       ],
       "timeFields": [
        { "timePath": "nodeData.datapoints.dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  generateDummyTimeseries(\n    from:$from,\n    to:$to,\n    nodeCount:2,\n    processorCount:4\n  ) {\n    serverName\n    nodeData {\n      nodeName\n      datapoints {\n        dateMillis\n        processorTemperatures {\n          processor\n          temperatureCelsius\n        }\n      }\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Generated Processor Temperatures (Uses \"Partition by values\" transform) (first node only)",
   "type": "timeseries",
   "description": "Note: The labels do not appear correctly on Grafana 9.3\n\nThis tests whether specifying data paths containing arrays and indexing into them works.\n\nBecause this is the first node only, we expect the temperatures between the processors to all be pretty similar.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "generateDummyTimeseries.nodeData.0",
       "explodeArrayPaths": [
        "datapoints.processorTemperatures"
       ],
       "timeFields": [
        { "timePath": "datapoints.dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  generateDummyTimeseries(\n    from:$from,\n    to:$to,\n    nodeCount:2,\n    processorCount:4\n  ) {\n    serverName\n    nodeData {\n      nodeName\n      datapoints {\n        dateMillis\n        processorTemperatures {\n          processor\n          temperatureCelsius\n        }\n      }\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Generated Processor Temperatures (Uses Wild GraphQL labels) (Frame exclude feature)",
   "type": "timeseries",
   "description": "Same as the above graph, except it uses Wild GraphQL labels.\n\nThis tests the \"Frame exclude\" feature of labels.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "generateDummyTimeseries",
       "explodeArrayPaths": [
        "nodeData.datapoints.processorTemperatures"
       ],
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "excludeFieldFromDataFrame": true,
          "required": true
         },
         "name": "server",
         "type": "field",
         "value": "serverName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "excludeFieldFromDataFrame": true,
          "required": true
         },
         "name": "node",
         "type": "field",
         "value": "nodeData.nodeName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "excludeFieldFromDataFrame": true,
          "required": true
         },
         "name": "processor",
         "type": "field",
         "value": "nodeData.datapoints.processorTemperatures.processor"
        }
       ],
       "timeFields": [
        { "timePath": "nodeData.datapoints.dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  generateDummyTimeseries(\n    from:$from,\n    to:$to,\n    nodeCount:2,\n    processorCount:4\n  ) {\n    serverName\n    nodeData {\n      nodeName\n      datapoints {\n        dateMillis\n        processorTemperatures {\n          processor\n          temperatureCelsius\n        }\n      }\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Generated Processor Temperatures (Uses Wild GraphQL labels) (Explode array of primitives, #index feature)",
   "type": "timeseries",
   "description": "Similar to the other graphs, but the query itself returns an array of numbers representing the temperature in Celsius.\n\nThis tests exploding arrays of primitives and the beta feature of referencing a #index field within a label. Additionally, whether \"Frame exclude\" is checked should not affect whether the #index field is included in the data frame (#index fields and any field containing \"#\" will never be included in the data frame).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "generateDummyTimeseries",
       "explodeArrayPaths": [
        "nodeData.datapoints.processorTemperaturesCelsius"
       ],
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "excludeFieldFromDataFrame": true,
          "required": true
         },
         "name": "server",
         "type": "field",
         "value": "serverName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "excludeFieldFromDataFrame": true,
          "required": true
         },
         "name": "node",
         "type": "field",
         "value": "nodeData.nodeName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "processor",
         "type": "field",
         "value": "nodeData.datapoints.processorTemperaturesCelsius#index"
        }
       ],
       "timeFields": [
        { "timePath": "nodeData.datapoints.dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  generateDummyTimeseries(\n    from:$from,\n    to:$to,\n    nodeCount:2,\n    processorCount:4\n  ) {\n    serverName\n    nodeData {\n      nodeName\n      datapoints {\n        dateMillis\n        processorTemperaturesCelsius\n      }\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Generated Processor Temperatures (Uses Wild GraphQL labels) (expected to contain glitched datapoints)",
   "type": "timeseries",
   "description": "Same as the above graph, except it uses Wild GraphQL labels.\n\nThis version of the dashboard does not use the \"Frame exclude\" feature, and we therefore expect the node number to be included as a data point (which results in weird graph).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "generateDummyTimeseries",
       "explodeArrayPaths": [
        "nodeData.datapoints.processorTemperatures"
       ],
       "labelOptions": [
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "server",
         "type": "field",
         "value": "serverName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "node",
         "type": "field",
         "value": "nodeData.nodeName"
        },
        {
         "fieldConfig": {
          "defaultValue": "",
          "required": true
         },
         "name": "processor",
         "type": "field",
         "value": "nodeData.datapoints.processorTemperatures.processor"
        }
       ],
       "timeFields": [
        { "timePath": "nodeData.datapoints.dateMillis" }
       ]
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  generateDummyTimeseries(\n    from:$from,\n    to:$to,\n    nodeCount:2,\n    processorCount:4\n  ) {\n    serverName\n    nodeData {\n      nodeName\n      datapoints {\n        dateMillis\n        processorTemperatures {\n          processor\n          temperatureCelsius\n        }\n      }\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Queries that should result in errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "Expect error \"serverName is not an object or array\"",
   "type": "table",
   "description": "In this query we set the data path to point to an element that is not an object or an array. We expect an error to occur",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "generateDummyTimeseries.serverName",
       "explodeArrayPaths": [],
       "timeFields": []
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  generateDummyTimeseries(\n    from:$from,\n    to:$to,\n    nodeCount:2,\n    processorCount:4\n  ) {\n    serverName\n    nodeData {\n      nodeName\n      datapoints {\n        dateMillis\n        processorTemperatures {\n          processor\n          temperatureCelsius\n        }\n      }\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Expect error \"should be an integer\"",
   "type": "table",
   "description": "In this query we set the data path to point to an array, and incorrectly attempt to use \"a\" to index into that array, causing an integer parsing error.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "generateDummyTimeseries.nodeData.a",
       "explodeArrayPaths": [],
       "timeFields": []
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  generateDummyTimeseries(\n    from:$from,\n    to:$to,\n    nodeCount:2,\n    processorCount:4\n  ) {\n    serverName\n    nodeData {\n      nodeName\n      datapoints {\n        dateMillis\n        processorTemperatures {\n          processor\n          temperatureCelsius\n        }\n      }\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Expect GraphQL error \"Expected header to be present\"",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "echoHttpHeaders",
       "timeFields": []
      }
     ],
     "queryText": "query {\n  echoHttpHeaders {\n  \tactuallyUnexpected:expectHeader(name:\"whyWouldThisBeAHeader\")\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Expect error \"doesNotExist does not exist\"",
   "type": "table",
   "description": "In this query we set the data path to something that does not exist.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "doesNotExist",
       "explodeArrayPaths": [],
       "timeFields": []
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  generateDummyTimeseries(\n    from:$from,\n    to:$to,\n    nodeCount:2,\n    processorCount:4\n  ) {\n    serverName\n    nodeData {\n      nodeName\n      datapoints {\n        dateMillis\n        processorTemperatures {\n          processor\n          temperatureCelsius\n        }\n      }\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Expect error \"should be non-negative integer\"",
   "type": "table",
   "description": "In this query we set the data path to point to an array, and incorrect index using a negative integer",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "generateDummyTimeseries.nodeData.-1",
       "explodeArrayPaths": [],
       "timeFields": []
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  generateDummyTimeseries(\n    from:$from,\n    to:$to,\n    nodeCount:2,\n    processorCount:4\n  ) {\n    serverName\n    nodeData {\n      nodeName\n      datapoints {\n        dateMillis\n        processorTemperatures {\n          processor\n          temperatureCelsius\n        }\n      }\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Expect error \"must not fall out of bounds\"",
   "type": "table",
   "description": "In this query we set the data path to point to an array, and incorrectly index that array using a value we expect to be out of bounds",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "parsingOptions": [
      {
       "dataPath": "generateDummyTimeseries.nodeData.2",
       "explodeArrayPaths": [],
       "timeFields": []
      }
     ],
     "queryText": "query ($from: Long!, $to: Long!) {\n  generateDummyTimeseries(\n    from:$from,\n    to:$to,\n    nodeCount:2,\n    processorCount:4\n  ) {\n    serverName\n    nodeData {\n      nodeName\n      datapoints {\n        dateMillis\n        processorTemperatures {\n          processor\n          temperatureCelsius\n        }\n      }\n    }\n  }\n}\n"
    }
   ]
  }
 ]
}